### ISSUE TITLE
Notifications do not work.

### ISSUE THREAD

**Issue by scoopex** [eladnava/applicationize#127]
Thanks for running this great project.

Unfortunately i do not receive desktop notifications although i activated "Would you like applications to be able to send you notifications?" with my testing webapp.

My testing app operates as a PWA using a service worker which receives notifications by firebase or a websocket.

**Comment by eladnava** [comment]
Hi @scoopex,
At this time, Applicationize doesn't support service workers due to missing functionality in the Chromium `<webview>`. This is missing functionality upstream. The only currently supported notifications are local desktop notifications, issued by the app via the local [Notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) API.

In the meantime, I would recommend simply using a built in feature baked into Chrome which supports remote push notifications.

There is a new feature in Google Chrome called Application Shortcuts. It basically makes it possible to convert any web page (or web app) into a desktop app by clicking the hamburger icon in the top right -> More Tools -> Create Shortcut and ticking "Open as window". Please give it a try and let me know if it supports these features.
