### ISSUE TITLE
External Link Issues

### ISSUE THREAD

**Issue by dotsona07** [eladnava/applicationize#15]
I am having an issue where some external links will open in a new chrome window and some don't. The issue is I cant get back to my main app (I am doing this with google photos). Any ideas on how to fix this :) I think the easy fix for this is to make all external links open in a new chrome window (in the actual browser) rather than the native app. To keep the app more isolated from a UX standpoint.

**Comment by eladnava** [comment]
Hi Andrew! =)

The way it's implemented right now, is that we let the web app decide whether to open a link in a new window or not. `<a>` links in the web app that contain the `target="_blank"` attribute will open in a new tab [thanks to this code](https://github.com/eladnava/applicationize/blob/927bcddd5bf92b9e9a6300fad3887bd1bfffbdf5/assets/crx/js/embed.js#L8) and those that did not declare `target="_blank"` won't.

I think this is expected behavior because some links actually lead you to another section of the web app.

Check out the Google Photos sidebar, for example:

![screen shot 2016-04-28 at 12 07 10 am](https://cloud.githubusercontent.com/assets/4394189/14868215/2dc597ec-0cd5-11e6-8056-804c27a430b1.png)

All of these links should not open in a new window. All of them, except for Privacy and Terms at the very bottom, and if you click them, you'll see that Google indeed declared them as `target="_blank"`.

By the way, you can navigate backwards within the web app window by clicking the `Delete` key on Mac (`Backspace` in Windows).

What do you think?
