### ISSUE TITLE
Popup windows open outside of app

### ISSUE THREAD

**Issue by markmcintyre** [eladnava/applicationize#18]
It would be nice if pop-up windows could open up within the app instead of a separate browser instance. 

Links with `target="_blank"` currently open in another instance, which makes perfect sense to me, but any window that opens in a popup (via `window.open`, for example) is usually part of the host application and should open up in the applicationized instance instead of the browser.

**Comment by eladnava** [comment]
Hey @markmcintyre,

Thanks for reporting this bug! I have just issued a fix and deployed it to applicationize.me/now. Let me know how it works for you! =)

**Comment by markmcintyre** [comment]
Thanks for the quick work!

One issue: New windows generated by the Outlook Web App are all blank. I'm not sure what method Outlook is using to populate the new windows, so I'm not sure how to recommend a fix. It might be something unusual on the web application's end.

**Comment by eladnava** [comment]
@markmcintyre this must be because Outlook Web App opens a new popup to `about:blank` and then issues a JavaScript / `<meta>` redirect, as described here:
http://stackoverflow.com/a/18452171/1123355

> If such a website is wrapped in a webview, everything becomes more difficult: e.targetUrl in the 'newwindow' handler above will contain "about:blank", so without modification the code will open a blank window/tab. To intercept the subsequent redirect from the guest, the app will also have to use the chrome.webRequest API (the documentation appears to be for extensions only, but the API is already available for packaged apps in the stable channel, too)

The code for detecting this is pretty ugly and would require us to start requesting the `webRequest` permission to install the extension, something that might seem fishy to some users. I'm going to close this for now unless you can think of a solution to this problem that doesn't include a new shady permission or hacky code. =)

In any case, most pop-ups will work as expected now.

**Comment by eladnava** [comment]
#31 now provides an option to open links outside of the app.

**Comment by eladnava** [comment]
Reopening this since the `about:blank` issue is still occurring.

**Comment by eladnava** [comment]
`about:blank` issue relocated to #36 since it is not related to the original issue posted here.

**Comment by bradhenderson07** [comment]
I love the idea of the app but it doesn't work for logging in to a lot of apps. For example, I can't even get into feedly because of the pop-up that comes up when you try to log in. I was finally able to get into Asana by creating a Username and password but I was having the same problem as feedly when I tried signing in with Google.

**Comment by eladnava** [comment]
@bradhenderson07 Consider a possible workaround here:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260
