### ISSUE TITLE
When closing the last window inside the app, we cannot get back to the original app URL again without quitting and relaunching

### ISSUE THREAD

**Issue by Zuldra** [eladnava/applicationize#53]
Hello and thanks for this nice tool.

I'm attempting to use Applicationize for Google Sheets and Google Docs.

The app always needs to have at least one window open, because otherwise I will never be able to get back to the Applicationized URL (https://docs.google.com/spreadsheets/u/0/) to open another file again.

If the window has been closed, the only way to make the app functional again is to quit the app, and restart it.

Opening a new window should be available within the File menu, and it should go back to the Applicationized URL.

I hope this can be resolved when the App is hosted again.

Thanks

**Comment by eladnava** [comment]
Hi @Zuldra,
Thanks for your report, however, I cannot reproduce this issue. 

When I close the last applicationized window, the application terminates completely. I must reopen it from the Google App Launcher or OSX Launchpad. I did not find that I have to quit any app since it is already terminated automatically.

Maybe try updating your Chrome version?

**Comment by Zuldra** [comment]
eladnava,

On your suggestion to be more critical of Chrome itself, I tried updating and deleting my Chrome user profile and the issue has gone away. Now I can't reproduce it! This can be closed. If it ever comes back I will report.

Thank you.

**Comment by eladnava** [comment]
Happy to hear this is resolved!
