### ISSUE TITLE
"google docs" generated app Conflict with "google drive"

### ISSUE THREAD

**Issue by asfktz** [eladnava/applicationize#8]
steps:
1. generate app with this url: https://docs.google.com/document/u/0/
2. drag generated file to "Extensions" tab

![image](https://cloud.githubusercontent.com/assets/199747/13827925/b31bb216-ebc7-11e5-9dc0-095222ded1d9.png)

**Comment by eladnava** [comment]
Hi @asfktz, thanks for submitting the issue, and welcome to Applicationize!

This is indeed strange behavior, especially since you probably don't have the Google Drive extension installed.

I found a suitable workaround, though. Try generating an app for [doc.google.com](https://doc.google.com/) instead:
`https://doc.google.com/document/u/0/`

It redirects to the [docs.google.com](https://docs.google.com) subdomain automatically, and Chrome won't give you any trouble.

**Comment by eladnava** [comment]
Hi @asfktz,
This no longer occurs after the https://github.com/eladnava/applicationize/commit/66b6b3f77e9257e94ec83c0d61d00d35394189c9 commit. Extensions now utilize a background script that embeds the applicationized URL instead of a "hosted app" type of approach.

Let me know if you still have trouble,
Elad
