### ISSUE TITLE
stay running onload?

### ISSUE THREAD

**Issue by brentley** [eladnava/applicationize#81]
What would it take to have the application stay running all the time? Could we add a generic enough funcion using `chrome.app.runtime.onStartup.addListener(function()` that something like facebook messenger, or whatsapp web could give us notifications even if we forgot to launch the application?

**Comment by brentley** [comment]
would it be possible to just load a second copy of the site into a hidden page? (background.html?) so that notifications could still come through?

**Comment by eladnava** [comment]
Hi @brentley,
The application will stay running if you simply hide it using `Command + H`. Don't quit the app and you will continue receiving desktop notifications. For Web Push notifications, even closing the app should keep them coming.

**Comment by eladnava** [comment]
Closing due to lack of response. Please feel free to comment if you still need help with this.

**Comment by brentley** [comment]
Hi @eladnava, sorry for not responding sooner... 
Ideally I wouldn't have to open the app. To give you an example, my "messages" app is a PWA, but somehow is running even if I haven't yet opened it. When I get a SMS to my phone, the alert shows up in my notification area on my pixelbook. 

As I research, it looks like I just need to applicationize a background.html in addition to the main site, allowing the background.html page to keep the connection open, whether the main "application" is open or not.

Anyway, that's the ask. I know I could open/minimize, but I'm looking for something even more "integrated" feeling than that.

**Comment by eladnava** [comment]
Hi @brentley,
With Applicationize we make use of the `<webview>` to embed the target website in a Chrome App window. No window, no website. 

While Applicationize does support Desktop Notifications (local notifications created by the target website), remote notifications (Web Push) and PWA apps require **service worker registration** and this isn't something currently supported by Applicationize. 

The good news is that you can now register service workers in Chrome extensions:
https://bugs.chromium.org/p/chromium/issues/detail?id=501569

However, since this is not a popular request by other users of Applicationize, you will have to implement this yourself. Good luck 👍
