### ISSUE TITLE
Microphone permissions not activating

### ISSUE THREAD

**Issue by mattrossman** [eladnava/applicationize#89]
I have enabled "Would you like applications to be able to record audio via microphone?" under advanced options. I generated an applicationized extension for https://voice.google.com to access the Google Voice service.

When I try to place a call, the app tells me that [I need to enable microphone permissions](https://i.imgur.com/qsBj94M.png) in my browser to proceed.

I am running Chrome Version 74.0.3729.169 on a 2018 MacBook Pro.

**Comment by eladnava** [comment]
Hi @mattrossman,
Thanks so much for reporting this issue. 

This issue was introduced when I migrated the project to generate `CRXv3` extensions. The permissions selected under `(advanced options)` no longer made it to the `manifest.json` file.

This has now been fixed, please re-generate your Applicationize app, reinstall, and test it out:
https://applicationize.me/now
