### ISSUE TITLE
Chrome OS 75 removes downloaded crx packages

### ISSUE THREAD

**Issue by hiking93** [eladnava/applicationize#90]
Chrome OS 75 automatically removes crx packages when downloaded, maybe for security reasons.

![Screenshot 2019-06-01 at 13 55 06](https://user-images.githubusercontent.com/3449834/58744419-437fcd80-8475-11e9-90bb-beb6e21ecd77.png)

Chrome OS Version 75.0.3770.61 (Official Build) beta (64-bit)

Maybe providing an option to download unpacked extension could help? For drag-and-drop sideload.

**Comment by eladnava** [comment]
Hi @hiking93,
Thanks for reporting this issue.

Since I'm on the Stable release channel of Chrome I don't yet have access to Chrome 75. When they push the update, if it still breaks Applicationize `.crx` downloads, we shall indeed offer an alternative solution, probably in the form of renaming the extension of the download (from `.crxtmp` to `.crx` for example). 👍

**Comment by eladnava** [comment]
Resolved via https://github.com/eladnava/applicationize/commit/253aead795cad7b256f229e0018f8e258e3f7ee4 (workaround).

Please try again:
https://applicationize.me/now
