### ISSUE TITLE
Can't add Chrome extension to app

### ISSUE THREAD

**Issue by msi-matthew** [eladnava/applicationize#94]
I'd like to add a chrome extension after a web app is created.

There doesn't seem to be an integration for this.

**Comment by eladnava** [comment]
Hi @msi-matthew,
Please clarify.

I'm not sure what you're looking to get done.

**Comment by msi-matthew** [comment]
It would be nice to be able to run extensions within these web apps.

e.g. https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb?hl=en

**Comment by eladnava** [comment]
Ah, understood. Unfortunately since we use Chrome Packaged Apps to embed the target web app using the `<webview>` tag, other Extensions can't hook their way inside and affect the displayed webpage.

However, there is a workaround that involves using a built-in Chrome app packaging feature:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260

Please try and let me know if it works.

Related: #21.

**Comment by msi-matthew** [comment]
Hm... that flag / feature doesn't appear to exist anymore...

**Comment by eladnava** [comment]
@msi-matthew It's most likely built-in and enabled by default now.

On Mac:

3 dots icon in top right -> More Tools -> ***Create Shortcut***.

**Comment by msi-matthew** [comment]
Awesome. Thank you!!
