### ISSUE TITLE
Any way to set the default zoom on the created app?

### ISSUE THREAD

**Issue by jhoward15** [eladnava/applicationize#98]
Is there a way to set the default zoom (to something else than 100%) or even zoom (via hotkeys) on the created app? The ctl+plus keys aren't working on the created app. Thanks.

**Comment by jhoward15** [comment]
trying ctl+plus key

**Comment by jhoward15** [comment]
I did confirm that in Chrome itself the page zooms with CTL+= key(the same key the plus is on) but does not zoom with the same page application-ized. CTL+SHIFT+= key (or what would be + then) zooms the whole operating system - taskbar and all. Attached is the screenshot of the zoom keys pressed in regular Chrome (which did zoom it). Thanks for your help.
![keypress](https://user-images.githubusercontent.com/3316021/66654231-64b0b180-ebff-11e9-8106-65fccf923de0.png)

**Comment by eladnava** [comment]
@jhoward15 Awesome, thanks for confirming!

The bug was caused because Applicationize was checking for Windows in the OS platform name, and only then was it going to use the `e.ctrlKey` property to detect whether `Ctrl` is being held down:
https://github.com/eladnava/applicationize/commit/74b9f1a6b8fb758c8b6a46674989b15226aa314c

Instead, I inverted the logic to use `e.metaKey` for `Mac` only (which on Mac is the `command` key).

Please re-create your Applicationized app here and try again:
https://applicationize.me/now

**Comment by jhoward15** [comment]
Fix works perfectly. Thanks for the fast help!
